sonar.projectKey=Michela-M_the-plant-project
sonar.organization=michela-m

# Optional but recommended
sonar.projectName=the-plant-project
sonar.projectVersion=1.0

# Where your source code lives (React apps usually use src/)
sonar.sources=src

# Encoding
sonar.sourceEncoding=UTF-8
